services:
  ha-fusion-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      # Prevent overwriting container's node_modules
      - /app/node_modules
    ports:
      - "${DEV_PORT:-5173}:5173"
    environment:
      TZ: ${TZ:-UTC}
      HASS_URL: ${HASS_URL}
      NODE_ENV: development
    restart: unless-stopped
