---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-ha-fusion.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "my-ha-fusion.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-ha-fusion.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-ha-fusion.name" . }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.pvcName }}
              mountPath: /app/data
          env:
            - name: TZ
              value: {{ .Values.env.TZ }}
            - name: HASS_URL
              value: {{ .Values.env.HASS_URL }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: {{ .Values.pvcName }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}
