---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-ha-fusion.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "my-ha-fusion.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "my-ha-fusion.name" . }}