---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default .Values.pvcName .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ default .Values.storageClassName "" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}